require('config/options')
require('config/vars')
require('config/statusline')
require('config/maps')
require('config/commands')
require('config/autocmds')
require('plugin/lsp')
require('plugin/telescope')
-- require('plugin/treesitter')
