require('config/options')
require('config/vars')
require('config/statusline')
require('config/maps')
require('config/commands')
require('config/autocmds')
require('plugin/lsp')
require('plugin/telescope')
-- require('plugin/treesitter')

require("which-key").setup()
require("nvim-tree").setup()
require("stabilize").setup()
vim.cmd [[colorscheme gruvbox]]
require("colorizer").setup()
