local M = {}

function M.get(p)
  return {
    -- Editor UI
    Normal = { fg = p.fg, bg = p.bg },
    NormalFloat = { fg = p.fg, bg = p.bg_float },
    NormalNC = { fg = p.fg, bg = p.bg },
    Visual = { bg = p.bg_visual },
    VisualNOS = { bg = p.bg_visual },
    Cursor = { fg = p.bg, bg = p.cursor },
    lCursor = { fg = p.bg, bg = p.cursor },
    CursorIM = { fg = p.bg, bg = p.cursor },
    CursorLine = { bg = p.bg_highlight },
    CursorColumn = { bg = p.bg_highlight },
    CursorLineNr = { fg = p.fg_gutter_active },
    LineNr = { fg = p.fg_gutter },
    SignColumn = { fg = p.fg_gutter, bg = p.bg },
    ColorColumn = { bg = p.bg_highlight },
    Folded = { fg = p.comment, bg = p.bg_float },
    FoldColumn = { fg = p.fg_gutter },
    VertSplit = { fg = p.border },
    WinSeparator = { fg = p.border },
    StatusLine = { fg = p.fg_dim, bg = p.bg_dim },
    StatusLineNC = { fg = p.fg_gutter, bg = p.bg_dim },
    TabLine = { fg = p.fg_dim, bg = p.bg_dim },
    TabLineSel = { fg = p.fg, bg = p.bg },
    TabLineFill = { bg = p.bg_dim },
    Pmenu = { fg = p.fg, bg = p.bg_float },
    PmenuSel = { bg = p.bg_visual },
    PmenuSbar = { bg = p.bg_float },
    PmenuThumb = { bg = p.fg_gutter },
    Search = { fg = p.fg, bg = p.bg_search },
    IncSearch = { fg = p.bg, bg = p.cursor },
    CurSearch = { fg = p.bg, bg = p.cursor },
    Substitute = { fg = p.bg, bg = p.error },
    MatchParen = { fg = p.accent, bold = true },
    SpecialKey = { fg = p.whitespace },
    NonText = { fg = p.whitespace },
    Whitespace = { fg = p.whitespace },
    WildMenu = { bg = p.bg_visual },
    FloatBorder = { fg = p.border, bg = p.bg_float },
    FloatTitle = { fg = p.fg, bg = p.bg_float, bold = true },
    WinBar = { fg = p.fg, bg = p.bg },
    WinBarNC = { fg = p.fg_dim, bg = p.bg },
    Directory = { fg = p.func },
    Title = { fg = p.func, bold = true },
    ErrorMsg = { fg = p.error },
    WarningMsg = { fg = p.warn },
    MoreMsg = { fg = p.info },
    Question = { fg = p.info },
    ModeMsg = { fg = p.fg, bold = true },
    QuickFixLine = { bg = p.bg_visual },
    Conceal = { fg = p.fg_dim },
    EndOfBuffer = { fg = p.bg },

    -- Spell
    SpellBad = { sp = p.error, undercurl = true },
    SpellCap = { sp = p.warn, undercurl = true },
    SpellLocal = { sp = p.info, undercurl = true },
    SpellRare = { sp = p.hint, undercurl = true },

    -- Diff
    DiffAdd = { bg = p.diff_add },
    DiffChange = { bg = p.diff_change },
    DiffDelete = { bg = p.diff_delete },
    DiffText = { bg = p.diff_text },

    -- Syntax (legacy groups)
    Comment = { fg = p.comment, italic = true },
    Constant = { fg = p.constant },
    String = { fg = p.string },
    Character = { fg = p.string },
    Number = { fg = p.number },
    Boolean = { fg = p.number },
    Float = { fg = p.number },
    Identifier = { fg = p.fg },
    Function = { fg = p.func },
    Statement = { fg = p.keyword, bold = true },
    Conditional = { fg = p.keyword, bold = true },
    Repeat = { fg = p.keyword, bold = true },
    Label = { fg = p.keyword, bold = true },
    Operator = { fg = p.operator },
    Keyword = { fg = p.keyword, bold = true },
    Exception = { fg = p.keyword, bold = true },
    PreProc = { fg = p.keyword },
    Include = { fg = p.keyword, bold = true },
    Define = { fg = p.keyword },
    Macro = { fg = p.decorator },
    PreCondit = { fg = p.keyword },
    Type = { fg = p.type, italic = true },
    StorageClass = { fg = p.keyword, bold = true },
    Structure = { fg = p.type, italic = true },
    Typedef = { fg = p.type, italic = true },
    Special = { fg = p.operator },
    SpecialChar = { fg = p.regex },
    Tag = { fg = p.tag, bold = true },
    Delimiter = { fg = p.punctuation },
    SpecialComment = { fg = p.comment, italic = true },
    Debug = { fg = p.warn },
    Underlined = { underline = true },
    Ignore = { fg = p.fg_dim },
    Error = { fg = p.error },
    Todo = { fg = p.cursor, bold = true },
    Added = { fg = p.added },
    Changed = { fg = p.modified },
    Removed = { fg = p.deleted },

    -- Treesitter captures
    ["@comment"] = { fg = p.comment, italic = true },
    ["@comment.documentation"] = { fg = p.comment, italic = true },
    ["@comment.todo"] = { fg = p.cursor, bold = true },
    ["@comment.note"] = { fg = p.info, bold = true },
    ["@comment.warning"] = { fg = p.warn, bold = true },
    ["@comment.error"] = { fg = p.error, bold = true },

    ["@string"] = { fg = p.string },
    ["@string.regex"] = { fg = p.regex },
    ["@string.escape"] = { fg = p.regex },
    ["@string.special"] = { fg = p.regex },
    ["@string.special.url"] = { fg = p.tag, underline = true },
    ["@string.special.symbol"] = { fg = p.string },

    ["@character"] = { fg = p.string },
    ["@character.special"] = { fg = p.regex },

    ["@number"] = { fg = p.number },
    ["@number.float"] = { fg = p.number },
    ["@boolean"] = { fg = p.number },

    ["@constant"] = { fg = p.constant },
    ["@constant.builtin"] = { fg = p.constant },
    ["@constant.macro"] = { fg = p.constant },

    ["@variable"] = { fg = p.fg },
    ["@variable.builtin"] = { fg = p.variable_lang, italic = true },
    ["@variable.member"] = { fg = p.member },
    ["@variable.parameter"] = { fg = p.parameter },

    ["@function"] = { fg = p.func },
    ["@function.call"] = { fg = p.func },
    ["@function.builtin"] = { fg = p.library_func },
    ["@function.macro"] = { fg = p.decorator },
    ["@function.method"] = { fg = p.func },
    ["@function.method.call"] = { fg = p.func },

    ["@keyword"] = { fg = p.keyword, bold = true },
    ["@keyword.coroutine"] = { fg = p.keyword, bold = true },
    ["@keyword.function"] = { fg = p.keyword, bold = true },
    ["@keyword.operator"] = { fg = p.operator },
    ["@keyword.import"] = { fg = p.keyword, bold = true },
    ["@keyword.type"] = { fg = p.keyword, bold = true },
    ["@keyword.modifier"] = { fg = p.keyword, bold = true },
    ["@keyword.repeat"] = { fg = p.keyword, bold = true },
    ["@keyword.return"] = { fg = p.keyword, bold = true },
    ["@keyword.debug"] = { fg = p.warn },
    ["@keyword.exception"] = { fg = p.keyword, bold = true },
    ["@keyword.conditional"] = { fg = p.keyword, bold = true },
    ["@keyword.conditional.ternary"] = { fg = p.operator },
    ["@keyword.directive"] = { fg = p.keyword },
    ["@keyword.directive.define"] = { fg = p.keyword },

    ["@type"] = { fg = p.type, italic = true },
    ["@type.builtin"] = { fg = p.type, italic = true },
    ["@type.definition"] = { fg = p.type, italic = true },
    ["@type.qualifier"] = { fg = p.keyword, bold = true },

    ["@attribute"] = { fg = p.decorator, italic = true },
    ["@attribute.builtin"] = { fg = p.decorator, italic = true },

    ["@property"] = { fg = p.property, italic = true },

    ["@operator"] = { fg = p.operator },

    ["@punctuation.bracket"] = { fg = p.punctuation },
    ["@punctuation.delimiter"] = { fg = p.punctuation_dim },
    ["@punctuation.special"] = { fg = p.interpolation },

    ["@tag"] = { fg = p.tag, bold = true },
    ["@tag.builtin"] = { fg = p.tag, bold = true },
    ["@tag.attribute"] = { fg = p.attribute },
    ["@tag.delimiter"] = { fg = p.tag },

    ["@constructor"] = { fg = p.type, italic = true },

    ["@module"] = { fg = p.string },
    ["@module.builtin"] = { fg = p.string },

    ["@label"] = { fg = p.keyword },

    ["@markup.heading"] = { fg = p.string, bold = true },
    ["@markup.italic"] = { fg = p.member, italic = true },
    ["@markup.strong"] = { bold = true },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.underline"] = { underline = true },
    ["@markup.quote"] = { fg = p.regex, italic = true },
    ["@markup.link"] = { fg = p.tag },
    ["@markup.link.url"] = { fg = p.tag, underline = true },
    ["@markup.link.label"] = { fg = p.info },
    ["@markup.raw"] = { fg = p.operator },
    ["@markup.raw.block"] = { fg = p.fg },
    ["@markup.list"] = { fg = p.func },
    ["@markup.list.checked"] = { fg = p.added },
    ["@markup.list.unchecked"] = { fg = p.fg_dim },
    ["@markup.math"] = { fg = p.number },

    ["@diff.plus"] = { fg = p.added },
    ["@diff.minus"] = { fg = p.deleted },
    ["@diff.delta"] = { fg = p.modified },

    -- LSP semantic tokens
    ["@lsp.type.class"] = { fg = p.type, italic = true },
    ["@lsp.type.decorator"] = { fg = p.decorator, italic = true },
    ["@lsp.type.enum"] = { fg = p.type, italic = true },
    ["@lsp.type.enumMember"] = { fg = p.regex },
    ["@lsp.type.function"] = { fg = p.func },
    ["@lsp.type.interface"] = { fg = p.type, italic = true },
    ["@lsp.type.keyword"] = { fg = p.keyword, bold = true },
    ["@lsp.type.macro"] = { fg = p.decorator },
    ["@lsp.type.method"] = { fg = p.func },
    ["@lsp.type.namespace"] = { fg = p.string },
    ["@lsp.type.number"] = { fg = p.number },
    ["@lsp.type.operator"] = { fg = p.operator },
    ["@lsp.type.parameter"] = { fg = p.parameter },
    ["@lsp.type.property"] = { fg = p.property, italic = true },
    ["@lsp.type.regexp"] = { fg = p.regex },
    ["@lsp.type.string"] = { fg = p.string },
    ["@lsp.type.struct"] = { fg = p.type, italic = true },
    ["@lsp.type.type"] = { fg = p.type, italic = true },
    ["@lsp.type.typeParameter"] = { fg = p.type, italic = true },
    ["@lsp.type.variable"] = {},
    ["@lsp.type.comment"] = {},
    ["@lsp.mod.defaultLibrary"] = {},
    ["@lsp.typemod.function.defaultLibrary"] = { fg = p.library_func },
    ["@lsp.typemod.method.defaultLibrary"] = { fg = p.library_func },
    ["@lsp.typemod.variable.defaultLibrary"] = { fg = p.variable_lang, italic = true },

    -- LSP diagnostics
    DiagnosticError = { fg = p.error },
    DiagnosticWarn = { fg = p.warn },
    DiagnosticInfo = { fg = p.info },
    DiagnosticHint = { fg = p.hint },
    DiagnosticOk = { fg = p.added },
    DiagnosticVirtualTextError = { fg = p.error, bg = p.diff_delete },
    DiagnosticVirtualTextWarn = { fg = p.warn, bg = p.diff_change },
    DiagnosticVirtualTextInfo = { fg = p.info, bg = p.diff_change },
    DiagnosticVirtualTextHint = { fg = p.hint },
    DiagnosticUnderlineError = { sp = p.error, undercurl = true },
    DiagnosticUnderlineWarn = { sp = p.warn, undercurl = true },
    DiagnosticUnderlineInfo = { sp = p.info, undercurl = true },
    DiagnosticUnderlineHint = { sp = p.hint, undercurl = true },
    DiagnosticFloatingError = { fg = p.error },
    DiagnosticFloatingWarn = { fg = p.warn },
    DiagnosticFloatingInfo = { fg = p.info },
    DiagnosticFloatingHint = { fg = p.hint },
    DiagnosticSignError = { fg = p.error },
    DiagnosticSignWarn = { fg = p.warn },
    DiagnosticSignInfo = { fg = p.info },
    DiagnosticSignHint = { fg = p.hint },

    -- LSP references
    LspReferenceText = { bg = p.bg_visual },
    LspReferenceRead = { bg = p.bg_visual },
    LspReferenceWrite = { bg = p.bg_visual },
    LspSignatureActiveParameter = { fg = p.cursor, bold = true },
    LspCodeLens = { fg = p.comment },
    LspInlayHint = { fg = p.fg_gutter },

    -- Telescope
    TelescopeNormal = { fg = p.fg, bg = p.bg_float },
    TelescopeBorder = { fg = p.border, bg = p.bg_float },
    TelescopeSelection = { bg = p.bg_visual },
    TelescopeSelectionCaret = { fg = p.accent },
    TelescopeMatching = { fg = p.accent, bold = true },
    TelescopePromptNormal = { fg = p.fg, bg = p.bg_float },
    TelescopePromptBorder = { fg = p.border, bg = p.bg_float },
    TelescopePromptTitle = { fg = p.bg, bg = p.accent, bold = true },
    TelescopePromptPrefix = { fg = p.accent },
    TelescopeResultsTitle = { fg = p.bg_float, bg = p.bg_float },
    TelescopePreviewTitle = { fg = p.bg, bg = p.added, bold = true },
    TelescopePreviewBorder = { fg = p.border, bg = p.bg_float },
    TelescopePreviewNormal = { fg = p.fg, bg = p.bg_float },

    -- Gitsigns
    GitSignsAdd = { fg = p.added },
    GitSignsChange = { fg = p.modified },
    GitSignsDelete = { fg = p.deleted },
    GitSignsCurrentLineBlame = { fg = p.fg_gutter },
    GitSignsAddInline = { bg = p.diff_add },
    GitSignsChangeInline = { bg = p.diff_change },
    GitSignsDeleteInline = { bg = p.diff_delete },

    -- Neo-tree
    NeoTreeNormal = { fg = p.fg_dim, bg = p.bg_dim },
    NeoTreeNormalNC = { fg = p.fg_dim, bg = p.bg_dim },
    NeoTreeDirectoryName = { fg = p.fg },
    NeoTreeDirectoryIcon = { fg = p.func },
    NeoTreeRootName = { fg = p.accent, bold = true },
    NeoTreeFileName = { fg = p.fg_dim },
    NeoTreeFileIcon = { fg = p.fg_dim },
    NeoTreeGitModified = { fg = p.modified },
    NeoTreeGitAdded = { fg = p.added },
    NeoTreeGitDeleted = { fg = p.deleted },
    NeoTreeGitConflict = { fg = p.error },
    NeoTreeGitUntracked = { fg = p.added },
    NeoTreeIndentMarker = { fg = p.indent_guide },
    NeoTreeExpander = { fg = p.fg_gutter },
    NeoTreeWinSeparator = { fg = p.border, bg = p.bg_dim },
    NeoTreeFloatBorder = { fg = p.border },
    NeoTreeFloatTitle = { fg = p.fg, bold = true },
    NeoTreeTitleBar = { fg = p.bg, bg = p.accent },
    NeoTreeDimText = { fg = p.fg_gutter },
    NeoTreeDotfile = { fg = p.fg_gutter },

    -- Barbar
    BufferCurrent = { fg = p.fg, bg = p.bg },
    BufferCurrentIndex = { fg = p.accent, bg = p.bg },
    BufferCurrentMod = { fg = p.cursor, bg = p.bg },
    BufferCurrentSign = { fg = p.accent, bg = p.bg },
    BufferCurrentIcon = { bg = p.bg },
    BufferCurrentTarget = { fg = p.error, bg = p.bg, bold = true },
    BufferVisible = { fg = p.fg_dim, bg = p.bg },
    BufferVisibleIndex = { fg = p.fg_dim, bg = p.bg },
    BufferVisibleMod = { fg = p.cursor, bg = p.bg },
    BufferVisibleSign = { fg = p.fg_gutter, bg = p.bg },
    BufferVisibleIcon = { bg = p.bg },
    BufferVisibleTarget = { fg = p.error, bg = p.bg, bold = true },
    BufferInactive = { fg = p.fg_gutter, bg = p.bg_dim },
    BufferInactiveIndex = { fg = p.fg_gutter, bg = p.bg_dim },
    BufferInactiveMod = { fg = p.cursor, bg = p.bg_dim },
    BufferInactiveSign = { fg = p.border, bg = p.bg_dim },
    BufferInactiveIcon = { bg = p.bg_dim },
    BufferInactiveTarget = { fg = p.error, bg = p.bg_dim, bold = true },
    BufferTabpages = { fg = p.accent, bg = p.bg_dim, bold = true },
    BufferTabpageFill = { bg = p.bg_dim },

    -- Mini.statusline
    MiniStatuslineDevinfo = { fg = p.fg_dim, bg = p.bg_highlight },
    MiniStatuslineFileinfo = { fg = p.fg_dim, bg = p.bg_highlight },
    MiniStatuslineFilename = { fg = p.fg_dim, bg = p.bg_dim },
    MiniStatuslineInactive = { fg = p.fg_gutter, bg = p.bg_dim },
    MiniStatuslineModeCommand = { fg = p.bg, bg = p.cursor, bold = true },
    MiniStatuslineModeInsert = { fg = p.bg, bg = p.added, bold = true },
    MiniStatuslineModeNormal = { fg = p.bg, bg = p.accent, bold = true },
    MiniStatuslineModeOther = { fg = p.bg, bg = p.info, bold = true },
    MiniStatuslineModeReplace = { fg = p.bg, bg = p.error, bold = true },
    MiniStatuslineModeVisual = { fg = p.bg, bg = p.keyword, bold = true },

    -- Which-key
    WhichKey = { fg = p.accent },
    WhichKeyGroup = { fg = p.info },
    WhichKeyDesc = { fg = p.fg },
    WhichKeySeparator = { fg = p.fg_gutter },
    WhichKeyFloat = { bg = p.bg_float },
    WhichKeyBorder = { fg = p.border, bg = p.bg_float },
    WhichKeyValue = { fg = p.fg_dim },

    -- Trouble
    TroubleNormal = { fg = p.fg, bg = p.bg_float },
    TroubleText = { fg = p.fg },
    TroubleCount = { fg = p.accent, bold = true },

    -- Flash
    FlashLabel = { fg = p.bg, bg = p.accent, bold = true },
    FlashMatch = { fg = p.fg, bg = p.bg_search },
    FlashCurrent = { fg = p.fg, bg = p.bg_search },
    FlashBackdrop = { fg = p.fg_gutter },

    -- Fidget
    FidgetTitle = { fg = p.accent, bold = true },
    FidgetTask = { fg = p.comment },

    -- Illuminate
    IlluminatedWordText = { bg = p.bg_visual },
    IlluminatedWordRead = { bg = p.bg_visual },
    IlluminatedWordWrite = { bg = p.bg_visual },

    -- Indent-blankline
    IblIndent = { fg = p.indent_guide },
    IblScope = { fg = p.indent_guide_active },
    IndentBlanklineChar = { fg = p.indent_guide },
    IndentBlanklineContextChar = { fg = p.indent_guide_active },

    -- Lazy
    LazyH1 = { fg = p.bg, bg = p.accent, bold = true },
    LazyButton = { fg = p.fg, bg = p.bg_float },
    LazyButtonActive = { fg = p.bg, bg = p.accent },
    LazySpecial = { fg = p.accent },

    -- Notify
    NotifyERRORBorder = { fg = p.error },
    NotifyWARNBorder = { fg = p.warn },
    NotifyINFOBorder = { fg = p.info },
    NotifyDEBUGBorder = { fg = p.comment },
    NotifyTRACEBorder = { fg = p.hint },
    NotifyERRORIcon = { fg = p.error },
    NotifyWARNIcon = { fg = p.warn },
    NotifyINFOIcon = { fg = p.info },
    NotifyDEBUGIcon = { fg = p.comment },
    NotifyTRACEIcon = { fg = p.hint },
    NotifyERRORTitle = { fg = p.error },
    NotifyWARNTitle = { fg = p.warn },
    NotifyINFOTitle = { fg = p.info },
    NotifyDEBUGTitle = { fg = p.comment },
    NotifyTRACETitle = { fg = p.hint },
  }
end

return M
