# Agent OS Configuration

# Refer to the official Agent OS documentation at:
# https://buildermethods.com/agent-os

agent_os_version: 1.4.1

agents:
  claude_code:
    enabled: true
  cursor:
    enabled: false

project_types:
  default:
    instructions: $HOME/.config/agent-os/instructions
    standards: $HOME/.config/agent-os/standards

  # type_a:
  #   instructions: ~/.agent-os/project_types/type_a/instructions
  #   standards: ~/.agent-os/project_types/type_a/standards

  # type_b:
  #   instructions: ~/.agent-os/project_types/type_b/instructions
  #   standards: ~/.agent-os/project_types/type_b/standards

default_project_type: default
